site_name: Acta Digital
theme:
  name: 'material'
  logo: img/logos/logo-acta-digital.svg
  favicon: img/logos/logo-acta-digital.svg
  language: 'es'
  feature:
    tabs: false
nav:
  - Inicio: index.md
  - Instructivos:
    - Personas:
      - App Acta Digital: instructivo-app.md
    - Entidades:
      - Alta Dispositivo: instructivo-alta-dispositivo.md
      - Alta Persona: instructivo-alta-persona.md
      - Control de Actas: instructivo-control.md
  - Preguntas Frecuentes: preguntas-frecuentes.md
  - Recomendaciones: recomendaciones.md
  - Acerca de: acerca.md
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - extra
