site_name: Acta Digital
site_url: http://ayuda.actadigital.com.ar/
theme:
  name: "material"
  logo: /img/logos/logo-acta-digital.svg
  favicon: /img/logos/logo-acta-digital.svg
  language: "es"
  feature:
    tabs: false
  font:
    text: Roboto
  palette:
    - scheme: default
      primary: red
      accent: yellow
      toggle:
        icon: material/weather-sunny
        name: Cambiar a Modo Oscuro
    - scheme: slate
      primary: red
      accent: yellow
      toggle:
        icon: material/weather-night
        name: Cambiar a Modo Claro
plugins:
  - search
  - minify:
      minify_html: true
      minify_js: true
      htmlmin_opts:
        remove_comments: true
nav:
  - Inicio: index.md
  - El sistema: sistema.md
  - Aplicación móvil: instructivos/app.md
  - Mis Actas: instructivos/mis-actas.md
  - Uso del celular entregado: instructivos/uso-celular-comodato.md
  - Preguntas frecuentes: preguntas-frecuentes/preguntas-frecuentes.md
  - Recomendaciones: preguntas-frecuentes/recomendaciones.md
  - Acerca de: acerca.md
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - extra
