site_name: Acta Digital
site_url: https://ayuda.actadigital.com.ar/es/latest/
theme:
  name: "material"
  logo: /es/latest/img/logos/logo-acta-digital.svg
  favicon: /es/latest/img/logos/logo-acta-digital.svg
  language: "es"
  feature:
    tabs: false
  font:
    text: Roboto
  palette:
    - scheme: default
      primary: red
      accent: yellow
      toggle:
        icon: material/weather-sunny
        name: Cambiar a Modo Oscuro
    - scheme: slate
      primary: red
      accent: yellow
      toggle:
        icon: material/weather-night
        name: Cambiar a Modo Claro
plugins:
  - search
  - minify:
      minify_html: true
      minify_js: true
      htmlmin_opts:
        remove_comments: true
nav:
  - Inicio: index.md
  - ¿Qué es Acta Digital?: sistema.md
  - Uso de la aplicación móvil: instructivos/app.md
  - Editar y controlar actas: instructivos/mis-actas.md
  - Uso del celular en comodato: instructivos/uso-celular-comodato.md
  - Preguntas frecuentes: preguntas-frecuentes.md
  - Recomendaciones: recomendaciones.md
  - Contacto: acerca.md
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - extra
