site_name: Acta Digital
theme:
  name: 'material'
  logo: img/logos/logox.png
  favicon: img/logos/logox.png
  language: 'es'
nav:
  - Altas: alta.md
  - Problemas conocidos: conocidos.md
  - Recomendaciones: recomendaciones.md

